# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Простые правила разметки
description: > # this means to ignore newlines until "baseurl:"
  Простые правила разметки HTML-документов, рекомендации по выбору HTML-элементов, примеры кода
baseurl: '/easy-markup' # the subpath of your site, e.g. /blog

# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: yoksel
github_username:  yoksel

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /title/

menu:
 - name: 'Введение'
   url: '/'
 - name: 'Первые шаги'
   url: '/first-steps/'
 - name: 'Как писать классы по БЭМ?'
   url: '/bem-rules/'
 - name: 'Примеры кода'
   url: '/examples/'
 - name: 'Капля магии'
   url: '/drop-of-magic/'
 - name: 'Тестируем всё'
   url: '/check-code/'
 - name: 'Поиск ошибок'
   url: '/catching-bugs/'
 - name: 'Доступность'
   url: '/accessibility/'

socials:
 - name: '@yoksel'
   url: 'https://twitter.com/yoksel'
 - name: 'Проект на GitHub'
   url: 'https://github.com/yoksel/easy-markup/'
