# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Простая разметка
description: > # this means to ignore newlines until "baseurl:"
  текст текст текст
baseurl: "" # the subpath of your site, e.g. /blog

# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: yoksel
github_username:  yoksel

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
